### ISSUE TITLE
IE9 - PDF viewer is rendering, but PDF not displaying

### ISSUE THREAD

**Issue by evapisces** [legalthings/angular-pdfjs-viewer#11]
I'm trying to render a PDF using IE9. The viewer renders on the screen, and when I click "Document Properties," I can see the info about the PDF. However, the PDF itself isn't being displayed. I did run the demo project in IE9 and that PDF is displaying fine.

**Comment by jasny** [comment]
Sorry, but we don't support any IE older than IE10. (Through PRs to fix IE9 issues are accepted.)
