### ISSUE TITLE
getting error on the "ReferenceError: PDFViewerApplication"

### ISSUE THREAD

**Issue by sundhar19** [legalthings/angular-pdfjs-viewer#21]
Hi,
thank you for posting such a nice article.
I have tried to setup this in IIS and tried using the demo.
I am getting the ReferenceError: PDFViewerApplication
any clues?

Regards
Kalyan

**Comment by jasny** [comment]
It looks like you didn't include `angular-pdfjs-viewer.js`.

If you can't get it to work, set it up on [jsfiddle](http://jsfiddle.net) so you can demonstrate the issue.

**Comment by NileshkumarPrajapati** [comment]
Hi, I am facing same issue even after include angular-pdfjs-viewer.js file in index

```
 <script src="Scripts/compatibility.js"></script>  /\* For old browser pdf.js */
 <script src="Scripts/pdf.js"></script>  
 <script src="Scripts/angular-pdfjs-viewer.js"></script>
```

i am getting refrence error from following line (#472). "PDFViewerApplication" is undefined.
  var pdfViewer = PDFViewerApplication.pdfViewer;

**Comment by mzmousa** [comment]
I'm getting the same error. @NileshkumarPrajapati @sundhar19 did you find a fix?

**Comment by NileshkumarPrajapati** [comment]
yes Muhammad, I have used one library to convert Html to PDF at client side in my project and it was creating issue. Please check all libraries which are used in your project.
