### ISSUE TITLE
Control over PDF Viewer UI

### ISSUE THREAD

**Issue by omatase** [legalthings/angular-pdfjs-viewer#23]
My requirement for displaying a PDF in my web application includes the requirements for: Print, Rotate, Zoom and Pop Out in New Window. I'd like to be able to customize the PDF viewer layout to remove some unneeded features, move the Rotate features to the main toolbar and add a button for Pop Out in New Window to the toolbar, but of course I don't want to go in and directly start editing the HTML. I can get part of the way toward my goal with just CSS but CSS alone won't work for all of my needs. 

There doesn't seem to be a supported strategy for this type of customization but am I wrong about that? If not, what is a recommendation for the best way to go about this? I'd like to do it in a way where, of course, I would still be eligible for updates made to the angular-pdfjs-viewer module in the future.

@jasny

**Comment by jasny** [comment]
@omatase Take a look at [legalthings/pdf.js-viewer](https://github.com/legalthings/pdf.js-viewer). It's a fork of a Mozilla demo project, therefor it doesn't lent itself that easily for use in an angular application.

Check which methods are exposed. You might need to add some customizations.

**Comment by omatase** [comment]
Thanks for responding @jasny. I just need a bit of clarification. Are you suggesting I *not* use the angular version of the pdfjs viewer or are you suggesting I look at the non-angular version for insight as to how to go about injecting a custom look and feel for the angular version?

**Comment by jasny** [comment]
@omatase The second: I am suggesting that you look at the non-angular version for insight as to how to go about injecting a custom look and feel for the angular version.

**Comment by omatase** [comment]
Thanks @jasny, where do I go to find that? The link you gave goes to a 404. Is it this one? https://github.com/legalthings/pdf.js-viewer

**Comment by jasny** [comment]
@omatase Yes

**Comment by omatase** [comment]
@jasny Thanks for your help. I didn't realize this before but after looking into it, you can do what I want to do by overriding the directive in a decorator. Pretty much exactly what I needed.

```
.config(function ($provide) {
    $provide.decorator('pdfjsViewerDirective', function ($delegate) {

        if ($delegate && $delegate.length > 0) {
            $delegate[0].templateUrl = '/Scripts/app/document-viewer/templates/pdf.js-viewer.html';
            $delegate[0].template = null;
        }

        return $delegate;
    });
});
```

Personally, with this as an option I don't see a reason for any specific feature to address customization.
