### ISSUE TITLE
How to use with Base64string PDF data ?

### ISSUE THREAD

**Issue by VinaykumarBhagwat** [legalthings/angular-pdfjs-viewer#24]
I have base64string pdf data (from API). Is there a way to pass any form of this to - pdfjs-viewer src ?

Tried various options which did NOT work -  
a. using binary data.    //window.atob(base64) 

b. using Object URL created from blob.
base64 converted to -> blob -> object URL -> pfjs-viewer src
Ex code:
let currentBlob: Blob = new Blob([byteArrayData], { type: 'application/pdf' });
this.pdfSrc = window.URL.createObjectURL(currentBlob);

Please suggest. Thank you.

**Comment by jasny** [comment]
Option b. should work, but might be broken. It's really an issue of [legalthings/pdf-viewer](https://github.com/legalthings/pdfjs-viewer).

**Comment by krusk8** [comment]
I'm interested to this functionality. The PDF in base64 string it's impossible to view on IE. Can you increase the priority. THank you.

**Comment by jasny** [comment]
@krusk8 We welcome a PR for this.

**Comment by Phanu282003** [comment]
Hi All,

I am doing about display pdf from web-api (string base64), so Could you please share the full source code about this?

Thanks!!
Boy

**Comment by FanFanFantastic** [comment]
Same I got stuck on converting from base64 to pdf

**Comment by championboylay** [comment]
Following is how I implemented to load pdf base64:
```
var binaryImg = atob(url);
var length = binaryImg.length;
var arrayBuffer = new ArrayBuffer(length);
var uintArray = new Uint8Array(arrayBuffer);

for (var i = 0; i < length; i++) {
  uintArray[i] = binaryImg.charCodeAt(i);
}
var currentBlob = new Blob([uintArray], {type: 'application/pdf'});
$scope.pdf =  URL.createObjectURL(currentBlob);
```
