### ISSUE TITLE
how get pdf loaded from server url

### ISSUE THREAD

**Issue by suraj740** [legalthings/angular-pdfjs-viewer#27]
pdfjs-viewer is working fine , but the thing is that i want to get pdf files from server and  not from the localhost.
so can you please tell how i can change this..
Thanks

**Comment by jasny** [comment]
You can set the `src` attribute to any URL to a PDF documents. The PDF does need to be publicly available, as this is a client side solution.

If you want to convert the PDF to HTML on server (running nodejs), check out the [html-pdf library](https://www.npmjs.com/package/html-pdf).
