### ISSUE TITLE
Can make it work on safari / iOS

### ISSUE THREAD

**Issue by spike886** [legalthings/angular-pdfjs-viewer#29]
It doesn't render the pdf after loading it on safari. It shows 3 warnings `Warning: Could not find preferred cmap table.`
But it works if you press the full screen button

**Comment by jasny** [comment]
Probably related to https://github.com/mozilla/pdf.js/issues/4800

That is specific that the PDF your testing with. Issue should go away when [pdfjs-viewer is upgraded](https://github.com/legalthings/angular-pdfjs-viewer/issues/9).
