### ISSUE TITLE
Load PDF from stream

### ISSUE THREAD

**Issue by mattobob** [legalthings/angular-pdfjs-viewer#30]
Is there a way to load PDFs from byte stream?
I have PDFs saved as byte array into DB, I would like to show them from within the viewer, but i only have "src" and it is supposed to open the document from an url.

**Comment by jasny** [comment]
@mattobob How does that data come from the server to the client? You must have some sort of server side script that gets the content from the DB and serves it over HTTP.

Just make sure you set the `Content-Type` header to `application/pdf` and you're good to go.

**Comment by jasny** [comment]
Note that if you're getting the PDF as base64 string, see #24
