### ISSUE TITLE
Issue PDF.js v1.1.215 (build: c9a7498) Message: Invalid PDF structure

### ISSUE THREAD

**Issue by theseeker16** [legalthings/angular-pdfjs-viewer#31]
![sin titulo](https://cloud.githubusercontent.com/assets/7884877/23741919/693085b0-0470-11e7-9b8f-df26112234a9.png)

**Comment by jasny** [comment]
Is probably solved when pdf.js is updated (see #13). In any case, this is an issue of pdf.js, not this AngularJS plugin.

**Comment by theseeker16** [comment]
@jasny thanks for Thanks for answering, actually i update the pdf.js from here https://mozilla.github.io/pdf.js/ but that version doesnt work with the angular-pdfjs-viewer.js, Another thing I'm programming from develop localhost:8080 I do not know if the src is wrong 
"$scope.pdf = {
            src: 'localhost:8080#/digitalBlog/viewer/leer/example.pdf'
        };"
the example.pdf is inside in the folder of my view and controller. I hope you can help me

**Comment by jasny** [comment]
No, you need the patched version. Please have patient, while we work on updating our fork.

**Comment by theseeker16** [comment]
Sorry for disturbing so much, the update will take a long time? The project must be delivered soon in 3 weeks, if not pitifully I will have to implement another angular-viewer. Thank you very so much

**Comment by jasny** [comment]
Probably not that long. There is a PR now, we have to review it. Not making any promises though.

**Comment by theseeker16** [comment]
Thank very so much, I hope to receive news soon

**Comment by moesjarraf** [comment]
@theseeker16 I believe this is not an issue of pdfjs. From what I can tell from your error pdfjs is not receiving the pdf you are intending for it to open. This could occur when it actually receives some html or an error message which could be accidental (server issue, wrong pdf path, etc).

Can you check in your browsers inspector (for chrome its F12) whether or not the pdf is actually being loaded **correctly**? You need to check the network tab and verify that the pdf being loaded is actually of the type pdf.

For the mozilla demo you would see something like this:

![image](https://cloud.githubusercontent.com/assets/5793511/23791747/80886920-0584-11e7-90e9-4afd03147211.png)

Note the response content-type is set to `application/pdf`. Also try opening the request url in another tab to check if the pdf is actually corrupt and/or check the response message, it should contain a binary representation of the pdf.

![image](https://cloud.githubusercontent.com/assets/5793511/23791943/46fc0404-0585-11e7-8a57-f614a6f712ae.png)

**Comment by theseeker16** [comment]
@moesjarraf 
![p2](https://cloud.githubusercontent.com/assets/7884877/23820681/ec0f73dc-05e3-11e7-91eb-06554bfc1d72.png)

the src of my pdf is wrong i thnk and i dont know how to solve 
![p1](https://cloud.githubusercontent.com/assets/7884877/23820691/18f215e4-05e4-11e7-8879-57a52ab48591.png)

this is my controller i put the pdf inside the directory but i dont know how to call that 
![p3](https://cloud.githubusercontent.com/assets/7884877/23820711/6aed31ee-05e4-11e7-8908-fda29742f956.png)

**Comment by theseeker16** [comment]
@moesjarraf 
![sin titulo](https://cloud.githubusercontent.com/assets/7884877/23820840/31a53f3c-05e7-11e7-88c5-23a82a9081b9.png)
 i resolver the problem he load the pdf. but he does not display content

**Comment by moesjarraf** [comment]
@theseeker16 That is just because you haven't styled it with CSS properly. It seems like you are displaying the pdf with absolute positioning? You have to make sure the pdf-viewer, or the container html element of it, has a width/height. Please see the [usage](https://github.com/legalthings/angular-pdfjs-viewer#usage) section of the readme on how we styled it for the demo.

You can see in your image that the pdf viewer is correctly displaying how many pages there are in the toolbar (1 out of 14), so the pdf has loaded, its just the styling you use that is causing it to not be displayed.

**Comment by jasny** [comment]
@theseeker16 @moesjarraf Please leave the issue tracker for bugs and feature requests. For how to use questions, please use [StackOverflow](http://www.stackoverflow.com). Thanks
