### ISSUE TITLE
viewer.css is not added in my index.html

### ISSUE THREAD

**Issue by xts-velkumars** [legalthings/angular-pdfjs-viewer#34]
Hi, 

i have added angular-pdfjs-viewer through below bower command. But viewer.css is not added in my index.html 

bower install angular-pdfjs-viewer --save

![image 19](https://cloud.githubusercontent.com/assets/13570225/24324322/02caa9ac-118d-11e7-9123-e20e0160bc4f.png)

js is added without any issues. 

![image 20](https://cloud.githubusercontent.com/assets/13570225/24324327/19af8af2-118d-11e7-8bc0-6ab082a7d144.png)

**Comment by ghost** [comment]
problably is this a file from pdf.js

**Comment by jasny** [comment]
@velkumars Please report an issue at https://github.com/legalthings/pdf.js-viewer
