### ISSUE TITLE
Access PDF's on a secure location

### ISSUE THREAD

**Issue by jegjessing** [legalthings/angular-pdfjs-viewer#35]
Hi, this really looks interesting.
There is one thing though.

To enable the viewer it needs the location of the pdf like src=...
Thing is, that the PDF's that we use must be protected and only accessed by users logged in. Just giving the src would not work in this case.
Is there a possibility for giving specific headers to it or setting data instead of src?
Then I could use angular for "downloading" the PDF into $scope.pdfdata
and then as argument for the viewer set data="pdfdata"

Hope you understand

**Comment by piwonesien** [comment]
something like this could solve this

**Controller:**
```
var BASE64_MARKER = ';base64,';

function convertDataURIToBinary(dataURI) {
    var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
    var base64 = dataURI.substring(base64Index);
    var raw = window.atob(base64);
    var rawLength = raw.length;
    var array = new Uint8Array(new ArrayBuffer(rawLength));

    for (var i = 0; i < rawLength; i++) {
        array[i] = raw.charCodeAt(i);
    }
    return array;
}

var pdfAsDataUri = "data:application/pdf;base64," + response.data; //response.data = BASE64 string of file
var pdfAsArray = convertDataURIToBinary(pdfAsDataUri);

var file = new Blob([pdfAsArray], { type: 'application/pdf' });
var fileURL = URL.createObjectURL(file);
$scope.pdf = $sce.trustAsResourceUrl(fileURL);
```


**View:**
```
<div class='some-pdf-container'>
    <pdfjs-viewer ng-src="{{pdf}}" scale="scale"
            download="true" print="false" open="false"
            on-init="onInit()" on-page-load="onPageLoad(page)">
    </pdfjs-viewer>
</div>
```

**Comment by jegjessing** [comment]
Thanks, I'll try that
No luck, I get webViewerLoad :-( though I have loaded pdf.js
