### ISSUE TITLE
Unable to Load PDF

### ISSUE THREAD

**Issue by umeshka** [legalthings/angular-pdfjs-viewer#37]
First of all thank a ton for providing such a wonderful pdf viewer for anularjs.
My issue i am not able to view pdf with the below code, but the toolbar is visible.

```
<pdfjs-viewer src="{{ pdf.src }}" scale="scale" download="false" print="false" open="false"  on-init="onInit()" on-page-load="onPageLoad(page)">
</pdfjs-viewer>
```

After doing the below code, i am able to view the pdf file but it is not working with boostrap col resize.

```
<div style="width: 800px; height: 550px;">
<pdfjs-viewer src="{{ pdf.src }}" scale="scale" download="false" print="false" open="false"  on-init="onInit()" on-page-load="onPageLoad(page)">
</pdfjs-viewer>
</div>
```

Please help me as i need to use this with bootstrap.

![image](https://cloud.githubusercontent.com/assets/22589628/24579958/5d43cb12-171d-11e7-9b95-a2bf0dcbe933.png)

**Comment by jasny** [comment]
@umeshka Please provide a [JSFiddle](https://jsfiddle.net/) showing the issue.

**Comment by umeshka** [comment]
I will create JSFiddle and let you know.

**Comment by umeshka** [comment]
I have created JsFiddle link  https://jsfiddle.net/r88n7h8e/4/
but it is not working.

**Comment by jasny** [comment]
@umeshka The javascript should just contain JS, not HTML. There is an external source menu option on the left. You can press the settings button next to `javascript` to select 'Angular' as JS framework.

**Comment by umeshka** [comment]
1. Unable to read pdf file
2. Bootstrap div are get overlapped.

![image](https://cloud.githubusercontent.com/assets/22589628/24942890/7300732c-1f71-11e7-9759-22b46e4dda69.png)

Actual Requirement is as per below image.
![image](https://cloud.githubusercontent.com/assets/22589628/24942950/cc04bece-1f71-11e7-80dc-bbd5d61f29e3.png)

**Comment by umeshka** [comment]
Hi Jasny,
i have created this link  https://jsfiddle.net/umesh_ka/r88n7h8e/134/
still unable to load pdf file, Can you pls help me to reslove this issue.

Thanks,
umeshka

**Comment by jasny** [comment]
@umeshka The HTML is completely broken causing issues. Make sure it's valid. Also you can just mix and match Bootstrap classes. Make sure you read the documentation.

Last, you can't load files over HTTP if your page is loaded over HTTP.

Anyway use the console to see the javascript errors.

**Comment by priyasadaiyappan** [comment]
Hi dear friends,
 i am unable to load the pdf in Pdf-viewer for angular js.. Please Some one to help to load the pdf.. Am i struggling at 6 days..if you knows means reply this message to quickly.. its urgent.. Mam Or Sir...
Warning message is coming like ****'PDFJS is not set! Make sure that pdf.js is loaded before angular-pdfjs-viewer.js is loaded.'**** otherwise nothing to display the screen in  web but already add the what ever js and css plugins are added 
 thanks
