### ISSUE TITLE
PDFJS.webViewerLoad is not a function

### ISSUE THREAD

**Issue by mowaiskalam** [legalthings/angular-pdfjs-viewer#43]
I have include PDF.js and also set the url of pdf.worker.js but still i am getting this error in console. What i am doing wrong ?

**Comment by mowaiskalam** [comment]
@jasny @KillaBee1985 @pranjal-goswami @subdee @sven4ask is anybody here to address this issue ?

**Comment by jasny** [comment]
This ticket is a duplicate of https://github.com/legalthings/angular-pdfjs-viewer/issues/38
