### ISSUE TITLE
vendor.worker.js not found

### ISSUE THREAD

**Issue by agam16** [legalthings/angular-pdfjs-viewer#48]
I am using gulp to create the build for my project.
The code is working perfectly via `gulp-serve` but when i try to use gulp build, it tries to find the worker file like `vendor.worker.js` which is not found.

What could be the issue?

**Comment by jasny** [comment]
The plugin will try to determine the paths automatically. But if you build / minify it often can't.

You need to set the paths explicitly. See [Advanced configuration in the README](https://github.com/legalthings/angular-pdfjs-viewer#advanced-configuration)
