### ISSUE TITLE
Embed inside HTML file

### ISSUE THREAD

**Issue by kegster** [legalthings/angular-pdfjs-viewer#5]
Can you show a demo of this implemented inside of an existing site?

Whenever I try to embed inside a <div></div> that's placed somewhere on a site, I get something like this:

http://imgur.com/meobVTw

Also, I get an error in the console:

> angular.js:12793ReferenceError: PDFViewerApplication is not defined
>     at angular-pdfjs-viewer.js:380
>     at s (angular.js:11610)
>     at m.$eval (angular.js:16321)
>     at m.$digest (angular.js:16139)
>     at m.$apply (angular.js:16429)
>     at angular.js:11600(anonymous function) @ angular.js:12793
> 387angular.js:12793 ReferenceError: PDFViewerApplication is not defined
>     at angular-pdfjs-viewer.js:380
>     at s (angular.js:11610)
>     at m.$eval (angular.js:16321)
>     at m.$digest (angular.js:16139)
>     at m.$apply (angular.js:16429)
>     at angular.js:11600(anonymous function) @ angular.js:12793(anonymous function) @ angular.js:9526m.$digest @ angular.js:16141m.$apply @ angular.js:16429(anonymous function) @ angular.js:11600

**Comment by moesjarraf** [comment]
@kegster Have you tried to run the [demo](https://github.com/legalthings/angular-pdfjs-viewer#demo) that is located within this repository? That should get you started. Also judging by your screenshot it looks like the dependencies aren't being loaded in the correct order, or from the wrong directory. They should be loaded like:

``` html
<script src="{{ bower directory }}/pdf.js-viewer/pdf.js"></script>
<link rel="stylesheet" href="{{ bower directory }}/pdf.js-viewer/viewer.css">

<script src="{{ bower directory }}/angular/angular.js"></script>
<script src="{{ bower directory }}/angular-pdfjs/dist/angular-pdfjs-viewer.js"></script>
<script src="app.js"></script>
```

**Comment by kegster** [comment]
The dependencies are being loaded in the order you describe.

I can't get a working demo into something outside of the demo itself.
Curious if it's meant to be placed in any div?

On Wed, Mar 30, 2016 at 6:03 PM, Moesjarraf J notifications@github.com
wrote:

> @kegster https://github.com/kegster Have you tried to run the demo
> https://github.com/legalthings/angular-pdfjs-viewer#demo that is
> located within this repository? That should get you started. Also judging
> by your screenshot it looks like the dependencies aren't being loaded in
> the correct order, or from the wrong directory. They should be loaded like:
> 
> <script src="{{ bower directory }}/pdf.js-viewer/pdf.js"></script>
> 
> <link rel="stylesheet" href="{{ bower directory }}/pdf.js-viewer/viewer.css">
> 
> <script src="{{ bower directory }}/angular/angular.js"></script>
> 
> <script src="{{ bower directory }}/angular-pdfjs/dist/angular-pdfjs-viewer.js"></script>
> 
> <script src="app.js"></script>
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/legalthings/angular-pdfjs-viewer/issues/5#issuecomment-203674758

## 

Cris Henderson

**Comment by moesjarraf** [comment]
You may place it in a div, although that is not the problem here. If the order is correct, then it means you are not loading the dependencies from the correct directories. Could you try looking through your browser's inspector (F12 in Chrome) and check the `Network` tab? You can see there which files are loaded and which response they give back to you.

**Comment by kegster** [comment]
I went ahead and loaded everything via bower and still same issue.

I have this PDF viewer loaded just fine:
https://github.com/sayanee/angularjs-pdf, using the $scope.pdfUrl ---

All I did was swap out the pdf embed code, remove the other viewer, and
then use {{ pdfUrl }} as my URL. Everything is loaded exactly as shown on
the instructions with bower.

I'm getting a "Can't interpolate: {{ pdfUrl }}" -- and now saying something
about a trusted Url source (trustAsResourceUrl or something) -- but I
didn't need this with my previous one.

Is there a reason I'm having such difficulty loading the "nicer" pdf viewer?

On Thu, Mar 31, 2016 at 6:33 AM, Moesjarraf J notifications@github.com
wrote:

> You may place it in a div, although that is not the problem here. If the
> order is correct, then it means you are not loading the dependencies from
> the correct directories. Could you try looking through your browser's
> inspector (F12 in Chrome) and check the Network tab? You can see there
> which files are loaded and which response they give back to you.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/legalthings/angular-pdfjs-viewer/issues/5#issuecomment-203889062

## 

Cris Henderson

**Comment by kegster** [comment]
OK I implemented the trustAsResourceUrl and I'm now getting a PDF viewer,
but it's blank. the PDF won't show. It's like a blank PDF now.

Refused to get unsafe header "Accept-Ranges" is the only error i get, if it
even applies to this situation.

On Thu, Mar 31, 2016 at 9:41 AM, Cris Henderson kegster@gmail.com wrote:

> I went ahead and loaded everything via bower and still same issue.
> 
> I have this PDF viewer loaded just fine:
> https://github.com/sayanee/angularjs-pdf, using the $scope.pdfUrl ---
> 
> All I did was swap out the pdf embed code, remove the other viewer, and
> then use {{ pdfUrl }} as my URL. Everything is loaded exactly as shown on
> the instructions with bower.
> 
> I'm getting a "Can't interpolate: {{ pdfUrl }}" -- and now saying
> something about a trusted Url source (trustAsResourceUrl or something) --
> but I didn't need this with my previous one.
> 
> Is there a reason I'm having such difficulty loading the "nicer" pdf
> viewer?
> 
> On Thu, Mar 31, 2016 at 6:33 AM, Moesjarraf J notifications@github.com
> wrote:
> 
> > You may place it in a div, although that is not the problem here. If the
> > order is correct, then it means you are not loading the dependencies from
> > the correct directories. Could you try looking through your browser's
> > inspector (F12 in Chrome) and check the Network tab? You can see there
> > which files are loaded and which response they give back to you.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/legalthings/angular-pdfjs-viewer/issues/5#issuecomment-203889062
> 
> ## 
> 
> Cris Henderson

## 

Cris Henderson

**Comment by kegster** [comment]
OK sorry for multiple messages, but trying to narrow it down and save you
time.

Right now the PDF viewer works perfectly, but the PDF is blank. Shows
correct # of pages, every page is blank, all the features work. Even the
print PDF and download PDF work (and show the whole PDF, not blank pages).

Any ideas?

I'm getting this, if it helps:
pdf.worker.js:34000 Refused to get unsafe header "Accept-Ranges"

On Thu, Mar 31, 2016 at 9:45 AM, Cris Henderson kegster@gmail.com wrote:

> OK I implemented the trustAsResourceUrl and I'm now getting a PDF viewer,
> but it's blank. the PDF won't show. It's like a blank PDF now.
> 
> Refused to get unsafe header "Accept-Ranges" is the only error i get, if
> it even applies to this situation.
> 
> On Thu, Mar 31, 2016 at 9:41 AM, Cris Henderson kegster@gmail.com wrote:
> 
> > I went ahead and loaded everything via bower and still same issue.
> > 
> > I have this PDF viewer loaded just fine:
> > https://github.com/sayanee/angularjs-pdf, using the $scope.pdfUrl ---
> > 
> > All I did was swap out the pdf embed code, remove the other viewer, and
> > then use {{ pdfUrl }} as my URL. Everything is loaded exactly as shown on
> > the instructions with bower.
> > 
> > I'm getting a "Can't interpolate: {{ pdfUrl }}" -- and now saying
> > something about a trusted Url source (trustAsResourceUrl or something) --
> > but I didn't need this with my previous one.
> > 
> > Is there a reason I'm having such difficulty loading the "nicer" pdf
> > viewer?
> > 
> > On Thu, Mar 31, 2016 at 6:33 AM, Moesjarraf J notifications@github.com
> > wrote:
> > 
> > > You may place it in a div, although that is not the problem here. If the
> > > order is correct, then it means you are not loading the dependencies from
> > > the correct directories. Could you try looking through your browser's
> > > inspector (F12 in Chrome) and check the Network tab? You can see there
> > > which files are loaded and which response they give back to you.
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/legalthings/angular-pdfjs-viewer/issues/5#issuecomment-203889062
> > 
> > ## 
> > 
> > Cris Henderson
> 
> ## 
> 
> Cris Henderson

## 

Cris Henderson

**Comment by kegster** [comment]
OK. I figured out the problem. I was using a different PDF viewer that wasn't as polished as yours apparently.
