### ISSUE TITLE
no resource to load, early way out

### ISSUE THREAD

**Issue by LYXmoonstars** [legalthings/angular-pdfjs-viewer#51]
I use data,
In the case that you cannot simply use the URL of the pdf, you can pass in raw data as a Uint8Array object. The data attribute takes a scope variable as its argument.

```
$scope.data = null; // this is loaded async

$http.get("http://example.com/file.pdf", {
    responseType: 'arraybuffer'
}).then(function (response) {
    $scope.data = new Uint8Array(response.data);
});
```

`$scope.data`  have database,but i use `<pdfjs-viewer data="$ctrl.data"></pdfjs-viewer>` in html,not pdf view ,Prompt： "no resource to load, early way out". I need your help, thank you.

**Comment by LYXmoonstars** [comment]
I will `data="$ctrl.data"` override `data="data"`，The PDF file is displayed.

**Comment by jasny** [comment]
Read https://stackoverflow.com/questions/11605917/this-vs-scope-in-angularjs-controllers
