### ISSUE TITLE
IE 11 Not working

### ISSUE THREAD

**Issue by wutkarin** [legalthings/angular-pdfjs-viewer#87]
IE 11 Not working

**Comment by sunit82** [comment]
i'm also facing the issue on IE 11. Error message below.
I'm trying to view a blob url using pdf viewer in a iframe. below is a sample url.
<iframe src ="http://localhost:1214/PDFjs/web/viewer.html?file=blob%3Ahttp%3A%2F%2Flocalhost%3A1214%2F4e72d48c-397f-4477-b88e-7a85c9c71557" ></iframe>

----------------------------------
PDF.js v1.9.426 (build: 2558a58d)
Message: undefined
-----------------------------------


In the IE debugger window I get following error - 
-----------------------------------
SCRIPT5007: Unable to get property 'prototype' of undefined or null reference
app.js (215,7)
-----------------------------------

please let me know there is a known bug and if there is any workaround.

**Comment by jasny** [comment]
Sorry IE is not supported.
