### ISSUE TITLE
PDF.js version update.

### ISSUE THREAD

**Issue by cataquil** [legalthings/angular-pdfjs-viewer#9]
The PDF.js version number that is in the pdf.js-viewer is 1.1.215 but the PDF.js github repo is on 1.4.20.

There is a printing issue with IE.  Is there anyway to update to the latest version of PDF.js?

**Comment by jasny** [comment]
pdf.js is bundled with the pdf.js viewer. We use a custom version of this viewer, so it can be embedded in an angular app. Unfortunately this makes updating not that straightforward.

I've created [detailed upgrade instructions](https://github.com/legalthings/pdf.js-viewer/tree/upgrade-instructions#upgrading-the-source). If the source hasn't change much, you can simply run `./build.sh` which will run use a patch file to modify the script.

If the source code has changed to much, `patch` will be unable to apply some of the chunks. In that case you need to apply the changes of these chunks by hand.

**Comment by moesjarraf** [comment]
Solved in https://github.com/legalthings/angular-pdfjs-viewer/pull/32
